stages:
  - build
  - test

test:mac:
  stage: test
  tags:
    - macos
  script:
    - pwd
    - source activate leaspy
    - python -m unittest discover tests
    - source deactivate

test:linux:
  stage: test
  tags:
    - linux
  script:
    - pwd
    - source activate leaspy
    - python -m unittest discover tests
    - source deactivate
